package com.example.freelancer.enums;

public enum NotificationType {

    // COMPANY
    COMPANY_APPROVED,
    COMPANY_REJECTED,

    // PROJECT
    PROJECT_APPROVED,
    PROJECT_REJECTED,
    PROJECT_ASSIGNED,
    PROJECT_DONE,
    PROJECT_CANCELLED,
    PROJECT_IN_PROGRESS,
    PROJECT_CREATED,
    PROJECT_UPDATED,
    PROJECT_PROGRESS_UPDATED,
    PROJECT_PAID,

    // PAYMENT
    PAYMENT_SUCCESS,
    PAYMENT_FAILED,
    PAYMENT_RECEIVED,
    PAYMENT_RULE_UPDATED,

    // WALLET
    WITHDRAW_SUCCESS,
    WITHDRAW_FAILED,

    // PROPOSAL
    PROPOSAL_ACCEPTED,
    PROPOSAL_REJECTED,

    // SYSTEM
    SYSTEM,
    // APPLICATION
    PROJECT_APPLIED,
    APPLICATION_REJECTED,
    APPLICATION_APPROVED,

    // TEAM
    LEADER_ASSIGNED,
    TEAM_MEMBER_ADDED,
    TEAM_MEMBER_REMOVED,
    // TASK
    TASK_ASSIGNED,
    TASK_CREATED,

    // ADMIN
    ADMIN_MESSAGE,
}
